#!/usr/bin/env python3
"""Збірка вебу (Prompt 19): webui/** -> src/net/web_assets_gen.cpp.

Кожен файл стискається gzip (рівень 9, mtime=0 -> детермінований вихід) і
вбудовується в прошивку масивом const uint8_t[] + таблицею kWebAssets[].

Два режими:
  * PlatformIO:  extra_scripts = pre:tools/build_web.py  (виконується перед кожною збіркою);
  * вручну:      python tools/build_web.py
Лише stdlib, Python 3.8+. Вивід скрипта - тільки ASCII (консоль Windows).
"""
import gzip
import io
import os
import sys

# ---------------------------------------------------------------------------
# Налаштування
# ---------------------------------------------------------------------------
WEBUI_DIR = "webui"
OUT_FILE = os.path.join("src", "net", "web_assets_gen.cpp")
BYTES_PER_LINE = 16
GZIP_LEVEL = 9

# Розширення -> MIME. Невідоме розширення = помилка (щоб не віддати файл зі сміттєвим типом).
MIME = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
    ".json": "application/json",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".txt": "text/plain; charset=utf-8",
}
# Текстові типи: CRLF -> LF перед стисканням (однаковий вихід на Windows і Linux).
TEXT_EXT = {".html", ".css", ".js", ".svg", ".json", ".txt"}

# ---------------------------------------------------------------------------
# Визначення кореня проєкту (PlatformIO / звичайний запуск)
# ---------------------------------------------------------------------------
try:
    Import("env")  # noqa: F821  (визначено лише всередині SCons/PlatformIO)
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
    IN_PIO = True
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    IN_PIO = False


def fail(msg):
    sys.stderr.write("[build_web] ERROR: %s\n" % msg)
    raise SystemExit(1)


def collect_files(root):
    """Повертає відсортований список (url_path, abs_path); dotfiles пропускає."""
    found = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in sorted(filenames):
            if name.startswith("."):
                continue
            abs_path = os.path.join(dirpath, name)
            rel = os.path.relpath(abs_path, root).replace(os.sep, "/")
            found.append(("/" + rel, abs_path))
    found.sort(key=lambda x: x[0])
    return found


def gzip_bytes(data):
    buf = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=buf,
                       compresslevel=GZIP_LEVEL, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def aliases_for(url):
    """Додаткові шляхи: /index.html -> /, /x.html -> /x."""
    if url == "/index.html":
        return ["/"]
    if url.endswith(".html"):
        return [url[:-5]]
    return []


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_cpp(assets):
    """assets: список dict(url, mime, gz, aliases)."""
    out = []
    w = out.append
    w("// AUTO-GENERATED by tools/build_web.py - DO NOT EDIT (file is in .gitignore).\n")
    w("// Source: webui/**, gzip level %d, mtime=0.\n\n" % GZIP_LEVEL)
    w('#include "net/web_assets.h"\n\nnamespace {\n\n')
    for i, a in enumerate(assets):
        w("// %s (%d bytes gzip)\n" % (a["url"], len(a["gz"])))
        w("const uint8_t kAsset%d[] = {\n" % i)
        gz = a["gz"]
        for pos in range(0, len(gz), BYTES_PER_LINE):
            chunk = gz[pos:pos + BYTES_PER_LINE]
            w("    " + ",".join("0x%02x" % b for b in chunk) + ",\n")
        w("};\n\n")
    w("}  // namespace\n\n")

    rows = []
    for i, a in enumerate(assets):
        for path in [a["url"]] + a["aliases"]:
            rows.append((path, a["mime"], i, len(a["gz"])))
    w("const WebAsset kWebAssets[] = {\n")
    for path, mime, i, n in rows:
        w("    {%s, %s, kAsset%d, %d},\n" % (c_string(path), c_string(mime), i, n))
    w("};\n\n")
    w("const size_t kWebAssetCount = %d;\n" % len(rows))
    return "".join(out), len(rows)


def main():
    root = os.path.join(PROJECT_DIR, WEBUI_DIR)
    out_path = os.path.join(PROJECT_DIR, OUT_FILE)
    if not os.path.isdir(root):
        fail("directory not found: %s" % root)

    assets = []
    for url, abs_path in collect_files(root):
        ext = os.path.splitext(url)[1].lower()
        if ext not in MIME:
            fail("unsupported file type '%s' (%s); add it to MIME" % (ext, url))
        with open(abs_path, "rb") as f:
            raw = f.read()
        if ext in TEXT_EXT:
            raw = raw.replace(b"\r\n", b"\n")
        assets.append({"url": url, "mime": MIME[ext], "raw": len(raw),
                       "gz": gzip_bytes(raw), "aliases": aliases_for(url)})
    if not assets:
        fail("no files under %s" % root)

    text, route_count = render_cpp(assets)
    new_bytes = text.encode("utf-8")

    old_bytes = None
    if os.path.isfile(out_path):
        with open(out_path, "rb") as f:
            old_bytes = f.read()
    changed = old_bytes != new_bytes
    if changed:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "wb") as f:
            f.write(new_bytes)

    print("[build_web] %-28s %9s %9s" % ("file", "raw", "gzip"))
    tot_raw = tot_gz = 0
    for a in assets:
        print("[build_web] %-28s %9d %9d" % (a["url"], a["raw"], len(a["gz"])))
        tot_raw += a["raw"]
        tot_gz += len(a["gz"])
    print("[build_web] %-28s %9d %9d" % ("TOTAL", tot_raw, tot_gz))
    print("[build_web] %d files, %d routes -> %s (%s)" % (
        len(assets), route_count, OUT_FILE.replace(os.sep, "/"),
        "updated" if changed else "unchanged"))


main()
